version: '3.9'
services:
  high:
    build:
      context: .
      dockerfile: Dockerfile.high
    ports:
      - 3000:3000
    command: yarn workspace @polar-view/high-bandwith start
    container_name: polar-view-high
    environment:
      - NEXT_PUBLIC_LOW_BANDWITH_URL=http://low:9000
  low:
    build:
      context: .
      dockerfile: Dockerfile.low
    ports:
      - 9000:8080
    command: yarn workspace @polar-view/low-bandwith serve
    container_name: polar-view-low
    environment:
      - HIGH_BANDWITH_URL=http://high:3000
